//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GiellyGreen_SelfInvoiceEntities : DbContext
    {
        public GiellyGreen_SelfInvoiceEntities()
            : base("name=GiellyGreen_SelfInvoiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Month_Header> Month_Header { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
    
        public virtual ObjectResult<DeleteSupplier_Result> DeleteSupplier(Nullable<int> supplierId)
        {
            var supplierIdParameter = supplierId.HasValue ?
                new ObjectParameter("SupplierId", supplierId) :
                new ObjectParameter("SupplierId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DeleteSupplier_Result>("DeleteSupplier", supplierIdParameter);
        }
    
        public virtual ObjectResult<GetAllSupplier_Result> GetAllSupplier(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllSupplier_Result>("GetAllSupplier", idParameter);
        }
    
        public virtual ObjectResult<InsertUpdateSupplier_Result> InsertUpdateSupplier(Nullable<int> supplierId, string supplierName, string supplierRef, string businessAddress, string email, string phone, string taxReference, string companyRegNumber, string companyRegAddress, string vatNumber, string logoUrl, Nullable<bool> isActive)
        {
            var supplierIdParameter = supplierId.HasValue ?
                new ObjectParameter("SupplierId", supplierId) :
                new ObjectParameter("SupplierId", typeof(int));
    
            var supplierNameParameter = supplierName != null ?
                new ObjectParameter("SupplierName", supplierName) :
                new ObjectParameter("SupplierName", typeof(string));
    
            var supplierRefParameter = supplierRef != null ?
                new ObjectParameter("SupplierRef", supplierRef) :
                new ObjectParameter("SupplierRef", typeof(string));
    
            var businessAddressParameter = businessAddress != null ?
                new ObjectParameter("BusinessAddress", businessAddress) :
                new ObjectParameter("BusinessAddress", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var taxReferenceParameter = taxReference != null ?
                new ObjectParameter("TaxReference", taxReference) :
                new ObjectParameter("TaxReference", typeof(string));
    
            var companyRegNumberParameter = companyRegNumber != null ?
                new ObjectParameter("CompanyRegNumber", companyRegNumber) :
                new ObjectParameter("CompanyRegNumber", typeof(string));
    
            var companyRegAddressParameter = companyRegAddress != null ?
                new ObjectParameter("CompanyRegAddress", companyRegAddress) :
                new ObjectParameter("CompanyRegAddress", typeof(string));
    
            var vatNumberParameter = vatNumber != null ?
                new ObjectParameter("VatNumber", vatNumber) :
                new ObjectParameter("VatNumber", typeof(string));
    
            var logoUrlParameter = logoUrl != null ?
                new ObjectParameter("LogoUrl", logoUrl) :
                new ObjectParameter("LogoUrl", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InsertUpdateSupplier_Result>("InsertUpdateSupplier", supplierIdParameter, supplierNameParameter, supplierRefParameter, businessAddressParameter, emailParameter, phoneParameter, taxReferenceParameter, companyRegNumberParameter, companyRegAddressParameter, vatNumberParameter, logoUrlParameter, isActiveParameter);
        }
    
        public virtual ObjectResult<InsetUpdateInvoices_Result> InsetUpdateInvoices(Nullable<int> id, Nullable<int> monthHeaderId, Nullable<int> supplierId, string supplierName, Nullable<decimal> hairService, Nullable<decimal> beautyService, Nullable<decimal> custom1, Nullable<decimal> custom2, Nullable<decimal> custom3, Nullable<decimal> custom4, Nullable<decimal> custom5, Nullable<decimal> net, Nullable<decimal> vat, Nullable<decimal> gross, Nullable<decimal> advancePaid, Nullable<decimal> balance, Nullable<bool> isApproved)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var monthHeaderIdParameter = monthHeaderId.HasValue ?
                new ObjectParameter("MonthHeaderId", monthHeaderId) :
                new ObjectParameter("MonthHeaderId", typeof(int));
    
            var supplierIdParameter = supplierId.HasValue ?
                new ObjectParameter("SupplierId", supplierId) :
                new ObjectParameter("SupplierId", typeof(int));
    
            var supplierNameParameter = supplierName != null ?
                new ObjectParameter("SupplierName", supplierName) :
                new ObjectParameter("SupplierName", typeof(string));
    
            var hairServiceParameter = hairService.HasValue ?
                new ObjectParameter("HairService", hairService) :
                new ObjectParameter("HairService", typeof(decimal));
    
            var beautyServiceParameter = beautyService.HasValue ?
                new ObjectParameter("BeautyService", beautyService) :
                new ObjectParameter("BeautyService", typeof(decimal));
    
            var custom1Parameter = custom1.HasValue ?
                new ObjectParameter("Custom1", custom1) :
                new ObjectParameter("Custom1", typeof(decimal));
    
            var custom2Parameter = custom2.HasValue ?
                new ObjectParameter("Custom2", custom2) :
                new ObjectParameter("Custom2", typeof(decimal));
    
            var custom3Parameter = custom3.HasValue ?
                new ObjectParameter("Custom3", custom3) :
                new ObjectParameter("Custom3", typeof(decimal));
    
            var custom4Parameter = custom4.HasValue ?
                new ObjectParameter("Custom4", custom4) :
                new ObjectParameter("Custom4", typeof(decimal));
    
            var custom5Parameter = custom5.HasValue ?
                new ObjectParameter("Custom5", custom5) :
                new ObjectParameter("Custom5", typeof(decimal));
    
            var netParameter = net.HasValue ?
                new ObjectParameter("Net", net) :
                new ObjectParameter("Net", typeof(decimal));
    
            var vatParameter = vat.HasValue ?
                new ObjectParameter("Vat", vat) :
                new ObjectParameter("Vat", typeof(decimal));
    
            var grossParameter = gross.HasValue ?
                new ObjectParameter("Gross", gross) :
                new ObjectParameter("Gross", typeof(decimal));
    
            var advancePaidParameter = advancePaid.HasValue ?
                new ObjectParameter("AdvancePaid", advancePaid) :
                new ObjectParameter("AdvancePaid", typeof(decimal));
    
            var balanceParameter = balance.HasValue ?
                new ObjectParameter("Balance", balance) :
                new ObjectParameter("Balance", typeof(decimal));
    
            var isApprovedParameter = isApproved.HasValue ?
                new ObjectParameter("IsApproved", isApproved) :
                new ObjectParameter("IsApproved", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InsetUpdateInvoices_Result>("InsetUpdateInvoices", idParameter, monthHeaderIdParameter, supplierIdParameter, supplierNameParameter, hairServiceParameter, beautyServiceParameter, custom1Parameter, custom2Parameter, custom3Parameter, custom4Parameter, custom5Parameter, netParameter, vatParameter, grossParameter, advancePaidParameter, balanceParameter, isApprovedParameter);
        }
    
        public virtual int UpdateStatus(Nullable<int> supplierId, Nullable<bool> isActive)
        {
            var supplierIdParameter = supplierId.HasValue ?
                new ObjectParameter("SupplierId", supplierId) :
                new ObjectParameter("SupplierId", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateStatus", supplierIdParameter, isActiveParameter);
        }
    }
}
